import os
import django
import requests
from io import BytesIO
from django.core.files.base import ContentFile
from django.core.management.base import BaseCommand
import random

from hospitals.models import Hospital

# Sample hospital images URLs (using placeholder service for demonstration)
HOSPITAL_IMAGES = [
    "https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=800&h=600",  # Modern hospital building
    "https://images.unsplash.com/photo-1551076805-e1869033e561?w=800&h=600",    # Hospital corridor
    "https://images.unsplash.com/photo-1538108149393-fbbd81895907?w=800&h=600",  # Hospital exterior
    "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&h=600",  # Medical facility
    "https://images.unsplash.com/photo-1563213126-a4273aed2016?w=800&h=600",    # Hospital building
]

def download_image(url, hospital_name):
    """Download image from URL and return ContentFile"""
    try:
        response = requests.get(url, timeout=10)
        response.raise_for_status()
        
        # Create a filename
        filename = f"{hospital_name.replace(' ', '_').lower()}.jpg"
        
        # Create ContentFile from response content
        image_content = ContentFile(response.content, name=filename)
        return image_content
    except Exception as e:
        print(f"Error downloading image for {hospital_name}: {e}")
        return None

# Hospital data for Indian hospitals across different states
HOSPITALS_DATA = [
    # Maharashtra
    {
        "name": "Kokilaben Dhirubhai Ambani Hospital",
        "state": "Maharashtra",
        "district": "Mumbai",
        "address": "Rao Saheb Achutrao Patwardhan Marg, Four Bungalows, Andheri West, Mumbai",
        "pincode": "400053",
        "category": "Multi-specialty",
        "phone": "+91-22-4269-6969",
        "email": "info@kokilabenhospital.com",
        "website": "https://www.kokilabenhospital.com",
        "bed_count": 750,
        "established_year": 2009,
        "accreditation": "NABH, JCI",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    
    # Himachal Pradesh
    {
        "name": "AIIMS Bilaspur",
        "state": "Himachal Pradesh",
        "district": "Bilaspur",
        "address": "Bilaspur, Himachal Pradesh",
        "pincode": "174001",
        "category": "Government Medical College",
        "phone": "+91-197-822-4000",
        "email": "info@aiimsbilaspur.edu.in",
        "website": "https://www.aiimsbilaspur.edu.in",
        "bed_count": 750,
        "established_year": 2019,
        "accreditation": "NABH",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    
    # Uttarakhand
    {
        "name": "AIIMS Rishikesh",
        "state": "Uttarakhand",
        "district": "Dehradun",
        "address": "Veerbhadra Road, Rishikesh",
        "pincode": "249203",
        "category": "Government Medical College",
        "phone": "+91-135-296-1000",
        "email": "info@aiimsrishikesh.edu.in",
        "website": "https://www.aiimsrishikesh.edu.in",
        "bed_count": 960,
        "established_year": 2012,
        "accreditation": "NABH",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    
    # Jammu & Kashmir
    {
        "name": "Sher-i-Kashmir Institute of Medical Sciences",
        "state": "Jammu & Kashmir",
        "district": "Srinagar",
        "address": "Bemina, Srinagar",
        "pincode": "190011",
        "category": "Government Medical Institute",
        "phone": "+91-194-240-1013",
        "email": "info@skims.ac.in",
        "website": "https://www.skims.ac.in",
        "bed_count": 650,
        "established_year": 1982,
        "accreditation": "NABH",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    
    # Goa
    {
        "name": "Goa Medical College Hospital",
        "state": "Goa",
        "district": "North Goa",
        "address": "Bambolim, Goa",
        "pincode": "403202",
        "category": "Government Medical College",
        "phone": "+91-832-245-8700",
        "email": "info@gmc.goa.gov.in",
        "website": "https://www.gmc.goa.gov.in",
        "bed_count": 1200,
        "established_year": 1963,
        "accreditation": "NABH",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    
    # Delhi
    {
        "name": "All India Institute of Medical Sciences",
        "state": "Delhi",
        "district": "New Delhi",
        "address": "Sri Aurobindo Marg, Ansari Nagar, New Delhi",
        "pincode": "110029",
        "category": "Government Medical College",
        "phone": "+91-11-2659-3333",
        "email": "info@aiims.edu",
        "website": "https://www.aiims.edu",
        "bed_count": 2478,
        "established_year": 1956,
        "accreditation": "NABH",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    
    # Karnataka
    {
        "name": "Manipal Hospital",
        "state": "Karnataka",
        "district": "Bangalore",
        "address": "98, Hal Airport Road, Bangalore",
        "pincode": "560017",
        "category": "Multi-specialty",
        "phone": "+91-80-2502-4444",
        "email": "info@manipalhospitals.com",
        "website": "https://www.manipalhospitals.com",
        "bed_count": 650,
        "established_year": 1991,
        "accreditation": "NABH, JCI",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    
    # Tamil Nadu
    {
        "name": "Apollo Hospital",
        "state": "Tamil Nadu",
        "district": "Chennai",
        "address": "21, Greams Lane, Off Greams Road, Chennai",
        "pincode": "600006",
        "category": "Multi-specialty",
        "phone": "+91-44-2829-3333",
        "email": "info@apollohospitals.com",
        "website": "https://www.apollohospitals.com",
        "bed_count": 550,
        "established_year": 1983,
        "accreditation": "NABH, JCI",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    
    # West Bengal
    {
        "name": "Apollo Gleneagles Hospital",
        "state": "West Bengal",
        "district": "Kolkata",
        "address": "58, Canal Circular Road, Kadapara, Kolkata",
        "pincode": "700054",
        "category": "Multi-specialty",
        "phone": "+91-33-2320-3040",
        "email": "info@apollohospitals.com",
        "website": "https://www.apollohospitals.com",
        "bed_count": 750,
        "established_year": 2005,
        "accreditation": "NABH, JCI",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    
    # More Maharashtra hospitals
    {
        "name": "Tata Memorial Hospital",
        "state": "Maharashtra",
        "district": "Mumbai",
        "address": "Dr E Borges Road, Parel, Mumbai",
        "pincode": "400012",
        "category": "Cancer Specialty",
        "phone": "+91-22-2417-7000",
        "email": "info@tmc.gov.in",
        "website": "https://www.tmc.gov.in",
        "bed_count": 629,
        "established_year": 1941,
        "accreditation": "NABH",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    {
        "name": "P.D. Hinduja National Hospital",
        "state": "Maharashtra",
        "district": "Mumbai",
        "address": "Veer Savarkar Marg, Mahim, Mumbai",
        "pincode": "400016",
        "category": "Multi-specialty",
        "phone": "+91-22-2445-2222",
        "email": "info@hindujahospital.com",
        "website": "https://www.hindujahospital.com",
        "bed_count": 350,
        "established_year": 1951,
        "accreditation": "NABH, JCI",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    {
        "name": "Breach Candy Hospital",
        "state": "Maharashtra",
        "district": "Mumbai",
        "address": "60-A, Bhulabhai Desai Road, Mumbai",
        "pincode": "400026",
        "category": "Multi-specialty",
        "phone": "+91-22-2367-8888",
        "email": "info@breachcandyhospital.org",
        "website": "https://www.breachcandyhospital.org",
        "bed_count": 165,
        "established_year": 1950,
        "accreditation": "NABH",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    {
        "name": "Jupiter Hospital",
        "state": "Maharashtra",
        "district": "Thane",
        "address": "Eastern Express Highway, Thane",
        "pincode": "400601",
        "category": "Multi-specialty",
        "phone": "+91-22-6269-2999",
        "email": "info@jupiterhospital.com",
        "website": "https://www.jupiterhospital.com",
        "bed_count": 355,
        "established_year": 2007,
        "accreditation": "NABH",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    {
        "name": "Jaslok Hospital",
        "state": "Maharashtra",
        "district": "Mumbai",
        "address": "15, Dr G Deshmukh Marg, Pedder Road, Mumbai",
        "pincode": "400026",
        "category": "Multi-specialty",
        "phone": "+91-22-6657-3333",
        "email": "info@jaslokhospital.net",
        "website": "https://www.jaslokhospital.net",
        "bed_count": 365,
        "established_year": 1973,
        "accreditation": "NABH, JCI",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    {
        "name": "Lilavati Hospital",
        "state": "Maharashtra",
        "district": "Mumbai",
        "address": "A-791, Bandra Reclamation, Bandra West, Mumbai",
        "pincode": "400050",
        "category": "Multi-specialty",
        "phone": "+91-22-2675-1000",
        "email": "info@lilavatihospital.com",
        "website": "https://www.lilavatihospital.com",
        "bed_count": 323,
        "established_year": 1978,
        "accreditation": "NABH",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    {
        "name": "Ruby Hall Clinic",
        "state": "Maharashtra",
        "district": "Pune",
        "address": "40, Sassoon Road, Pune",
        "pincode": "411001",
        "category": "Multi-specialty",
        "phone": "+91-20-2616-1000",
        "email": "info@rubyhall.com",
        "website": "https://www.rubyhall.com",
        "bed_count": 750,
        "established_year": 1959,
        "accreditation": "NABH, JCI",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    
    # More Delhi hospitals
    {
        "name": "Max Super Speciality Hospital",
        "state": "Delhi",
        "district": "South Delhi",
        "address": "1, Press Enclave Road, Saket, New Delhi",
        "pincode": "110017",
        "category": "Multi-specialty",
        "phone": "+91-11-2651-5050",
        "email": "info@maxhealthcare.com",
        "website": "https://www.maxhealthcare.in",
        "bed_count": 500,
        "established_year": 2006,
        "accreditation": "NABH, JCI",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    {
        "name": "BLK-Max Super Speciality Hospital",
        "state": "Delhi",
        "district": "West Delhi",
        "address": "Pusa Road, Rajinder Nagar, New Delhi",
        "pincode": "110005",
        "category": "Multi-specialty",
        "phone": "+91-11-3040-3040",
        "email": "info@blkmaxhospital.com",
        "website": "https://www.blkmaxhospital.com",
        "bed_count": 650,
        "established_year": 2009,
        "accreditation": "NABH, JCI",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    {
        "name": "Sir Ganga Ram Hospital",
        "state": "Delhi",
        "district": "Central Delhi",
        "address": "Rajinder Nagar, New Delhi",
        "pincode": "110060",
        "category": "Multi-specialty",
        "phone": "+91-11-2575-0000",
        "email": "info@sgrh.com",
        "website": "https://www.sgrh.com",
        "bed_count": 675,
        "established_year": 1954,
        "accreditation": "NABH, JCI",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    {
        "name": "Fortis Hospital",
        "state": "Delhi",
        "district": "South Delhi",
        "address": "B-22, Sector 62, Noida, Uttar Pradesh",
        "pincode": "201301",
        "category": "Multi-specialty",
        "phone": "+91-120-500-4444",
        "email": "info@fortishealthcare.com",
        "website": "https://www.fortishealthcare.com",
        "bed_count": 236,
        "established_year": 2001,
        "accreditation": "NABH, JCI",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    
    # More Karnataka hospitals
    {
        "name": "Narayana Health City",
        "state": "Karnataka",
        "district": "Bangalore",
        "address": "258/A, Bommasandra Industrial Area, Bangalore",
        "pincode": "560099",
        "category": "Multi-specialty",
        "phone": "+91-80-7122-2222",
        "email": "info@narayanahealth.org",
        "website": "https://www.narayanahealth.org",
        "bed_count": 1400,
        "established_year": 2000,
        "accreditation": "NABH, JCI",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    {
        "name": "Kidwai Memorial Institute of Oncology",
        "state": "Karnataka",
        "district": "Bangalore",
        "address": "Dr MH Marigowda Road, Bangalore",
        "pincode": "560029",
        "category": "Cancer Specialty",
        "phone": "+91-80-2659-4000",
        "email": "info@kidwai.kar.nic.in",
        "website": "https://www.kidwai.kar.nic.in",
        "bed_count": 1041,
        "established_year": 1973,
        "accreditation": "NABH",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    {
        "name": "Columbia Asia Hospital",
        "state": "Karnataka",
        "district": "Bangalore",
        "address": "Kirloskar Business Park, Bellary Road, Hebbal, Bangalore",
        "pincode": "560024",
        "category": "Multi-specialty",
        "phone": "+91-80-6132-0000",
        "email": "info@columbiaasia.com",
        "website": "https://www.columbiaasia.com",
        "bed_count": 200,
        "established_year": 2005,
        "accreditation": "NABH, JCI",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    {
        "name": "Fortis Hospital",
        "state": "Karnataka",
        "district": "Bangalore",
        "address": "154/9, Bannerghatta Road, Opposite IIM, Bangalore",
        "pincode": "560076",
        "category": "Multi-specialty",
        "phone": "+91-80-6621-4444",
        "email": "info@fortishealthcare.com",
        "website": "https://www.fortishealthcare.com",
        "bed_count": 400,
        "established_year": 2006,
        "accreditation": "NABH, JCI",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    {
        "name": "Kasturba Medical College Hospital",
        "state": "Karnataka",
        "district": "Manipal",
        "address": "Manipal, Udupi District",
        "pincode": "576104",
        "category": "Medical College Hospital",
        "phone": "+91-820-2922-201",
        "email": "info@manipal.edu",
        "website": "https://www.manipal.edu",
        "bed_count": 2032,
        "established_year": 1953,
        "accreditation": "NABH",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    
    # More Tamil Nadu hospitals
    {
        "name": "Fortis Malar Hospital",
        "state": "Tamil Nadu",
        "district": "Chennai",
        "address": "52, 1st Main Road, Gandhi Nagar, Adyar, Chennai",
        "pincode": "600020",
        "category": "Multi-specialty",
        "phone": "+91-44-4289-2222",
        "email": "info@fortishealthcare.com",
        "website": "https://www.fortishealthcare.com",
        "bed_count": 180,
        "established_year": 1992,
        "accreditation": "NABH, JCI",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    {
        "name": "Christian Medical College",
        "state": "Tamil Nadu",
        "district": "Vellore",
        "address": "Ida Scudder Road, Vellore",
        "pincode": "632004",
        "category": "Medical College Hospital",
        "phone": "+91-416-228-1000",
        "email": "info@cmcvellore.ac.in",
        "website": "https://www.cmcvellore.ac.in",
        "bed_count": 2938,
        "established_year": 1900,
        "accreditation": "NABH",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    {
        "name": "Sankara Nethralaya",
        "state": "Tamil Nadu",
        "district": "Chennai",
        "address": "18, College Road, Nungambakkam, Chennai",
        "pincode": "600006",
        "category": "Eye Specialty",
        "phone": "+91-44-2827-1616",
        "email": "info@sankaranethralaya.org",
        "website": "https://www.sankaranethralaya.org",
        "bed_count": 300,
        "established_year": 1978,
        "accreditation": "NABH",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    {
        "name": "Global Hospitals",
        "state": "Tamil Nadu",
        "district": "Chennai",
        "address": "439, Cheran Nagar, Perumbakkam, Chennai",
        "pincode": "600100",
        "category": "Multi-specialty",
        "phone": "+91-44-4777-7777",
        "email": "info@globalhospitalsindia.com",
        "website": "https://www.globalhospitalsindia.com",
        "bed_count": 350,
        "established_year": 2000,
        "accreditation": "NABH, JCI",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    {
        "name": "MIOT International",
        "state": "Tamil Nadu",
        "district": "Chennai",
        "address": "4/112, Mount Poonamalle Road, Manapakkam, Chennai",
        "pincode": "600089",
        "category": "Multi-specialty",
        "phone": "+91-44-2249-2000",
        "email": "info@miotinternational.com",
        "website": "https://www.miotinternational.com",
        "bed_count": 400,
        "established_year": 1999,
        "accreditation": "NABH, JCI",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    
    # Gujarat
    {
        "name": "HCG Cancer Centre",
        "state": "Gujarat",
        "district": "Ahmedabad",
        "address": "Sola Science City Road, Ahmedabad",
        "pincode": "380060",
        "category": "Cancer Specialty",
        "phone": "+91-79-4040-2000",
        "email": "info@hcgoncology.com",
        "website": "https://www.hcgoncology.com",
        "bed_count": 200,
        "established_year": 2009,
        "accreditation": "NABH",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    {
        "name": "Sterling Hospital",
        "state": "Gujarat",
        "district": "Ahmedabad",
        "address": "Behind Drive-in-Cinema, Mithakhali, Ahmedabad",
        "pincode": "380009",
        "category": "Multi-specialty",
        "phone": "+91-79-4040-4040",
        "email": "info@sterlinghospitals.com",
        "website": "https://www.sterlinghospitals.com",
        "bed_count": 350,
        "established_year": 2001,
        "accreditation": "NABH",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    {
        "name": "Apollo Hospital",
        "state": "Gujarat",
        "district": "Ahmedabad",
        "address": "Plot No 1A, GIDC Estate, Bhat, Gandhinagar",
        "pincode": "382428",
        "category": "Multi-specialty",
        "phone": "+91-79-6670-1000",
        "email": "info@apollohospitals.com",
        "website": "https://www.apollohospitals.com",
        "bed_count": 400,
        "established_year": 2010,
        "accreditation": "NABH, JCI",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    
    # More West Bengal hospitals
    {
        "name": "AMRI Hospital",
        "state": "West Bengal",
        "district": "Kolkata",
        "address": "P-4 & 5, CIT Scheme XLVIII, Gariahat Road, Kolkata",
        "pincode": "700019",
        "category": "Multi-specialty",
        "phone": "+91-33-6680-0000",
        "email": "info@amrihospitals.in",
        "website": "https://www.amrihospitals.in",
        "bed_count": 400,
        "established_year": 1996,
        "accreditation": "NABH",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    {
        "name": "Fortis Hospital",
        "state": "West Bengal",
        "district": "Kolkata",
        "address": "730, Anandapur, E M Bypass Road, Anandapur, Kolkata",
        "pincode": "700107",
        "category": "Multi-specialty",
        "phone": "+91-33-6628-4444",
        "email": "info@fortishealthcare.com",
        "website": "https://www.fortishealthcare.com",
        "bed_count": 400,
        "established_year": 2008,
        "accreditation": "NABH, JCI",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    
    # Rajasthan
    {
        "name": "Fortis Escorts Hospital",
        "state": "Rajasthan",
        "district": "Jaipur",
        "address": "Jawahar Lal Nehru Marg, Malviya Nagar, Jaipur",
        "pincode": "302017",
        "category": "Multi-specialty",
        "phone": "+91-141-254-7000",
        "email": "info@fortishealthcare.com",
        "website": "https://www.fortishealthcare.com",
        "bed_count": 355,
        "established_year": 2006,
        "accreditation": "NABH, JCI",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    {
        "name": "Sawai Man Singh Medical College",
        "state": "Rajasthan",
        "district": "Jaipur",
        "address": "Sawai Ram Singh Road, Jaipur",
        "pincode": "302004",
        "category": "Government Medical College",
        "phone": "+91-141-251-8121",
        "email": "info@smsmedicalcollege.com",
        "website": "https://www.smsmedicalcollege.com",
        "bed_count": 1750,
        "established_year": 1947,
        "accreditation": "NABH",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    {
        "name": "Apex Hospital",
        "state": "Rajasthan",
        "district": "Jaipur",
        "address": "Sector 43, Gurugram Road, Jaipur",
        "pincode": "302013",
        "category": "Multi-specialty",
        "phone": "+91-141-404-4000",
        "email": "info@apexhospitals.in",
        "website": "https://www.apexhospitals.in",
        "bed_count": 200,
        "established_year": 2008,
        "accreditation": "NABH",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    
    # Andhra Pradesh & Telangana
    {
        "name": "KIMS Hospital",
        "state": "Telangana",
        "district": "Hyderabad",
        "address": "1-8-31/1, Minister Rd, Krishna Nagar Colony, Begumpet, Secunderabad",
        "pincode": "500003",
        "category": "Multi-specialty",
        "phone": "+91-40-4488-5000",
        "email": "info@kimshospitals.com",
        "website": "https://www.kimshospitals.com",
        "bed_count": 500,
        "established_year": 2004,
        "accreditation": "NABH",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    {
        "name": "Yashoda Hospital",
        "state": "Telangana",
        "district": "Hyderabad",
        "address": "Behind Hari Hara Kala Bhawan, SP Road, Secunderabad",
        "pincode": "500003",
        "category": "Multi-specialty",
        "phone": "+91-40-2771-4444",
        "email": "info@yashodahospitals.com",
        "website": "https://www.yashodahospitals.com",
        "bed_count": 350,
        "established_year": 1989,
        "accreditation": "NABH, JCI",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    {
        "name": "Care Hospitals",
        "state": "Telangana",
        "district": "Hyderabad",
        "address": "Road No. 1, Banjara Hills, Hyderabad",
        "pincode": "500034",
        "category": "Multi-specialty",
        "phone": "+91-40-6165-6565",
        "email": "info@carehospitals.com",
        "website": "https://www.carehospitals.com",
        "bed_count": 435,
        "established_year": 1997,
        "accreditation": "NABH, JCI",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    {
        "name": "Apollo Hospital",
        "state": "Telangana",
        "district": "Hyderabad",
        "address": "Film Nagar, Jubilee Hills, Hyderabad",
        "pincode": "500033",
        "category": "Multi-specialty",
        "phone": "+91-40-2355-1066",
        "email": "info@apollohospitals.com",
        "website": "https://www.apollohospitals.com",
        "bed_count": 550,
        "established_year": 1988,
        "accreditation": "NABH, JCI",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    
    # Kerala
    {
        "name": "Amrita Institute of Medical Sciences",
        "state": "Kerala",
        "district": "Ernakulam",
        "address": "AIMS Ponekkara P.O., Kochi",
        "pincode": "682041",
        "category": "Medical College Hospital",
        "phone": "+91-484-285-1234",
        "email": "info@amrita.edu",
        "website": "https://www.amrita.edu",
        "bed_count": 1450,
        "established_year": 1998,
        "accreditation": "NABH, JCI",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    {
        "name": "Aster Medcity",
        "state": "Kerala",
        "district": "Ernakulam",
        "address": "Kuttisahib Road, Near Kothad Bridge, South Chittoor, Cheranalloor, Kochi",
        "pincode": "682027",
        "category": "Multi-specialty",
        "phone": "+91-484-669-4000",
        "email": "info@asterdmhealthcare.com",
        "website": "https://www.asterhospitals.in",
        "bed_count": 670,
        "established_year": 2014,
        "accreditation": "NABH, JCI",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    {
        "name": "Lakeshore Hospital",
        "state": "Kerala",
        "district": "Ernakulam",
        "address": "NH 47 Bypass, Maradu, Nettoor, Kochi",
        "pincode": "682040",
        "category": "Multi-specialty",
        "phone": "+91-484-270-1000",
        "email": "info@lakeshorehospital.com",
        "website": "https://www.lakeshorehospital.com",
        "bed_count": 300,
        "established_year": 2000,
        "accreditation": "NABH",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    
    # Punjab
    {
        "name": "Fortis Hospital",
        "state": "Punjab",
        "district": "Mohali",
        "address": "Sector 62, Phase - VIII, Mohali",
        "pincode": "160062",
        "category": "Multi-specialty",
        "phone": "+91-172-496-2000",
        "email": "info@fortishealthcare.com",
        "website": "https://www.fortishealthcare.com",
        "bed_count": 355,
        "established_year": 2007,
        "accreditation": "NABH, JCI",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    {
        "name": "Max Super Speciality Hospital",
        "state": "Punjab",
        "district": "Mohali",
        "address": "Phase VI, Sector 57, Mohali",
        "pincode": "160055",
        "category": "Multi-specialty",
        "phone": "+91-172-521-2000",
        "email": "info@maxhealthcare.com",
        "website": "https://www.maxhealthcare.in",
        "bed_count": 230,
        "established_year": 2009,
        "accreditation": "NABH, JCI",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    {
        "name": "PGIMER Chandigarh",
        "state": "Chandigarh",
        "district": "Chandigarh",
        "address": "Sector 12, Chandigarh",
        "pincode": "160012",
        "category": "Government Medical Institute",
        "phone": "+91-172-274-7585",
        "email": "info@pgimer.edu.in",
        "website": "https://www.pgimer.edu.in",
        "bed_count": 1900,
        "established_year": 1962,
        "accreditation": "NABH",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    
    # Haryana
    {
        "name": "Medanta - The Medicity",
        "state": "Haryana",
        "district": "Gurgaon",
        "address": "Sector 38, Gurugram",
        "pincode": "122001",
        "category": "Multi-specialty",
        "phone": "+91-124-414-1414",
        "email": "info@medanta.org",
        "website": "https://www.medanta.org",
        "bed_count": 1600,
        "established_year": 2009,
        "accreditation": "NABH, JCI",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    {
        "name": "Artemis Hospital",
        "state": "Haryana",
        "district": "Gurgaon",
        "address": "Sector 51, Gurugram",
        "pincode": "122001",
        "category": "Multi-specialty",
        "phone": "+91-124-451-1111",
        "email": "info@artemishospitals.com",
        "website": "https://www.artemishospitals.com",
        "bed_count": 600,
        "established_year": 2007,
        "accreditation": "NABH, JCI",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    {
        "name": "Paras Hospital",
        "state": "Haryana",
        "district": "Gurgaon",
        "address": "C-1, Sushant Lok Phase-I, Sector 43, Gurugram",
        "pincode": "122002",
        "category": "Multi-specialty",
        "phone": "+91-124-458-5555",
        "email": "info@parashospitals.com",
        "website": "https://www.parashospitals.com",
        "bed_count": 350,
        "established_year": 2006,
        "accreditation": "NABH",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    
    # Uttar Pradesh
    {
        "name": "Sanjay Gandhi Postgraduate Institute",
        "state": "Uttar Pradesh",
        "district": "Lucknow",
        "address": "Raebareli Road, Lucknow",
        "pincode": "226014",
        "category": "Government Medical Institute",
        "phone": "+91-522-249-4401",
        "email": "info@sgpgi.ac.in",
        "website": "https://www.sgpgi.ac.in",
        "bed_count": 1032,
        "established_year": 1983,
        "accreditation": "NABH",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    {
        "name": "Apollo Hospital",
        "state": "Uttar Pradesh",
        "district": "Lucknow",
        "address": "Kanpur - Lucknow Rd, Sector B, Bargawan, LDA Colony, Lucknow",
        "pincode": "226012",
        "category": "Multi-specialty",
        "phone": "+91-522-286-8888",
        "email": "info@apollohospitals.com",
        "website": "https://www.apollohospitals.com",
        "bed_count": 230,
        "established_year": 2019,
        "accreditation": "NABH",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    {
        "name": "King George's Medical University",
        "state": "Uttar Pradesh",
        "district": "Lucknow",
        "address": "Chowk, Lucknow",
        "pincode": "226003",
        "category": "Government Medical College",
        "phone": "+91-522-225-8401",
        "email": "info@kgmcindia.edu",
        "website": "https://www.kgmcindia.edu",
        "bed_count": 1500,
        "established_year": 1905,
        "accreditation": "NABH",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    
    # Bihar
    {
        "name": "Indira Gandhi Institute of Medical Sciences",
        "state": "Bihar",
        "district": "Patna",
        "address": "Sheikhpura, Patna",
        "pincode": "800014",
        "category": "Government Medical College",
        "phone": "+91-612-297-4021",
        "email": "info@igims.org",
        "website": "https://www.igims.org",
        "bed_count": 962,
        "established_year": 1983,
        "accreditation": "NABH",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    {
        "name": "Patna Medical College Hospital",
        "state": "Bihar",
        "district": "Patna",
        "address": "Ashok Raj Path, Patna",
        "pincode": "800004",
        "category": "Government Medical College",
        "phone": "+91-612-222-6995",
        "email": "info@pmch.bih.nic.in",
        "website": "https://www.pmch.bih.nic.in",
        "bed_count": 1300,
        "established_year": 1925,
        "accreditation": "NABH",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    
    # Odisha
    {
        "name": "AIIMS Bhubaneswar",
        "state": "Odisha",
        "district": "Bhubaneswar",
        "address": "Sijua, Patrapada, Bhubaneswar",
        "pincode": "751019",
        "category": "Government Medical College",
        "phone": "+91-674-247-3999",
        "email": "info@aiimsbhubaneswar.edu.in",
        "website": "https://www.aiimsbhubaneswar.edu.in",
        "bed_count": 960,
        "established_year": 2012,
        "accreditation": "NABH",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    {
        "name": "KIIT University Hospital",
        "state": "Odisha",
        "district": "Bhubaneswar",
        "address": "Campus 5, KIIT Deemed University, Bhubaneswar",
        "pincode": "751024",
        "category": "Private Medical College",
        "phone": "+91-674-272-7634",
        "email": "info@kiit.ac.in",
        "website": "https://www.kiit.ac.in",
        "bed_count": 500,
        "established_year": 2004,
        "accreditation": "NABH",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    
    # Assam
    {
        "name": "Gauhati Medical College Hospital",
        "state": "Assam",
        "district": "Guwahati",
        "address": "Bhangagarh, Guwahati",
        "pincode": "781032",
        "category": "Government Medical College",
        "phone": "+91-361-267-1202",
        "email": "info@gmch.gov.in",
        "website": "https://www.gmch.gov.in",
        "bed_count": 1500,
        "established_year": 1960,
        "accreditation": "NABH",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    {
        "name": "Apollo Excelcare Hospital",
        "state": "Assam",
        "district": "Guwahati",
        "address": "GS Road, Guwahati",
        "pincode": "781005",
        "category": "Multi-specialty",
        "phone": "+91-361-711-1000",
        "email": "info@apollohospitals.com",
        "website": "https://www.apollohospitals.com",
        "bed_count": 200,
        "established_year": 2008,
        "accreditation": "NABH",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    
    # Jharkhand
    {
        "name": "Rajendra Institute of Medical Sciences",
        "state": "Jharkhand",
        "district": "Ranchi",
        "address": "Bariatu, Ranchi",
        "pincode": "834009",
        "category": "Government Medical College",
        "phone": "+91-651-245-6201",
        "email": "info@rims.gov.in",
        "website": "https://www.rims.gov.in",
        "bed_count": 1200,
        "established_year": 1960,
        "accreditation": "NABH",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    {
        "name": "Tata Main Hospital",
        "state": "Jharkhand",
        "district": "East Singhbhum",
        "address": "Northern Town, Bistupur, Jamshedpur",
        "pincode": "831001",
        "category": "Corporate Hospital",
        "phone": "+91-657-665-5000",
        "email": "info@tatasteel.com",
        "website": "https://www.tatasteel.com",
        "bed_count": 750,
        "established_year": 1908,
        "accreditation": "NABH",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    
    # Madhya Pradesh
    {
        "name": "AIIMS Bhopal",
        "state": "Madhya Pradesh",
        "district": "Bhopal",
        "address": "Saket Nagar, Bhopal",
        "pincode": "462020",
        "category": "Government Medical College",
        "phone": "+91-755-267-2342",
        "email": "info@aiimsbhopal.edu.in",
        "website": "https://www.aiimsbhopal.edu.in",
        "bed_count": 960,
        "established_year": 2012,
        "accreditation": "NABH",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    {
        "name": "Bansal Hospital",
        "state": "Madhya Pradesh",
        "district": "Bhopal",
        "address": "B-253, Hill Road, Shahpura, Bhopal",
        "pincode": "462016",
        "category": "Multi-specialty",
        "phone": "+91-755-266-9999",
        "email": "info@bansalhospital.com",
        "website": "https://www.bansalhospital.com",
        "bed_count": 300,
        "established_year": 1999,
        "accreditation": "NABH",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    
    # Chhattisgarh
    {
        "name": "AIIMS Raipur",
        "state": "Chhattisgarh",
        "district": "Raipur",
        "address": "Great Eastern Road, Tatibandh, Raipur",
        "pincode": "492099",
        "category": "Government Medical College",
        "phone": "+91-771-297-1000",
        "email": "info@aiimsraipur.edu.in",
        "website": "https://www.aiimsraipur.edu.in",
        "bed_count": 960,
        "established_year": 2012,
        "accreditation": "NABH",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    {
        "name": "Ramkrishna Care Hospital",
        "state": "Chhattisgarh",
        "district": "Raipur",
        "address": "Aurobindo Enclave, Pachpedi Naka, Dhamtari Road, Raipur",
        "pincode": "492001",
        "category": "Multi-specialty",
        "phone": "+91-771-435-0100",
        "email": "info@rkcare.in",
        "website": "https://www.rkcare.in",
        "bed_count": 200,
        "established_year": 2010,
        "accreditation": "NABH",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    
    # Manipur
    {
        "name": "Regional Institute of Medical Sciences",
        "state": "Manipur",
        "district": "Imphal West",
        "address": "Lamphelpat, Imphal",
        "pincode": "795004",
        "category": "Government Medical College",
        "phone": "+91-385-241-4202",
        "email": "info@rims.edu.in",
        "website": "https://www.rims.edu.in",
        "bed_count": 650,
        "established_year": 1972,
        "accreditation": "NABH",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    
    # Meghalaya
    {
        "name": "North Eastern Indira Gandhi Regional Institute of Health & Medical Sciences",
        "state": "Meghalaya",
        "district": "East Khasi Hills",
        "address": "Mawdiangdiang, Shillong",
        "pincode": "793018",
        "category": "Government Medical Institute",
        "phone": "+91-364-253-6000",
        "email": "info@neigrihms.gov.in",
        "website": "https://www.neigrihms.gov.in",
        "bed_count": 650,
        "established_year": 1987,
        "accreditation": "NABH",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    
    # Tripura
    {
        "name": "Agartala Government Medical College",
        "state": "Tripura",
        "district": "West Tripura",
        "address": "Kunjaban, Agartala",
        "pincode": "799006",
        "category": "Government Medical College",
        "phone": "+91-381-232-5401",
        "email": "info@agmc.nic.in",
        "website": "https://www.agmc.nic.in",
        "bed_count": 500,
        "established_year": 2006,
        "accreditation": "NABH",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    
    # Mizoram
    {
        "name": "Civil Hospital Aizawl",
        "state": "Mizoram",
        "district": "Aizawl",
        "address": "Durtlang, Aizawl",
        "pincode": "796025",
        "category": "Government Hospital",
        "phone": "+91-389-233-4847",
        "email": "info@mizoramhealth.nic.in",
        "website": "https://www.mizoramhealth.nic.in",
        "bed_count": 350,
        "established_year": 1970,
        "accreditation": "NABH",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    
    # Nagaland
    {
        "name": "Naga Hospital Authority Kohima",
        "state": "Nagaland",
        "district": "Kohima",
        "address": "Kohima, Nagaland",
        "pincode": "797001",
        "category": "Government Hospital",
        "phone": "+91-370-224-0532",
        "email": "info@nhak.org",
        "website": "https://www.nhak.org",
        "bed_count": 300,
        "established_year": 2008,
        "accreditation": "NABH",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    
    # Arunachal Pradesh
    {
        "name": "Tomo Riba Institute of Health & Medical Sciences",
        "state": "Arunachal Pradesh",
        "district": "Naharlagun",
        "address": "Naharlagun, Arunachal Pradesh",
        "pincode": "791110",
        "category": "Government Medical Institute",
        "phone": "+91-360-224-3214",
        "email": "info@trihms.ac.in",
        "website": "https://www.trihms.ac.in",
        "bed_count": 500,
        "established_year": 2013,
        "accreditation": "NABH",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
    
    # Sikkim
    {
        "name": "Sir Thutob Namgyal Memorial Hospital",
        "state": "Sikkim",
        "district": "East Sikkim",
        "address": "Sochakgang, Gangtok",
        "pincode": "737101",
        "category": "Government Hospital",
        "phone": "+91-359-222-2988",
        "email": "info@stnmh.gov.in",
        "website": "https://www.stnmh.gov.in",
        "bed_count": 300,
        "established_year": 1917,
        "accreditation": "NABH",
        "emergency_services": True,
        "ambulance_service": True,
        "blood_bank": True,
        "pharmacy": True,
        "cafeteria": True,
        "parking_available": True,
    },
]

class Command(BaseCommand):
    help = 'Populate the database with hospital data'

    def handle(self, *args, **options):
        self.stdout.write("Starting hospital data population...")
        
        # Clear existing hospitals (optional)
        # Hospital.objects.all().delete()
        
        for i, hospital_data in enumerate(HOSPITALS_DATA):
            try:
                # Check if hospital already exists
                hospital, created = Hospital.objects.get_or_create(
                    name=hospital_data['name'],
                    defaults=hospital_data
                )
                
                if created:
                    # Download and assign image
                    image_url = random.choice(HOSPITAL_IMAGES)
                    image_content = download_image(image_url, hospital_data['name'])
                    
                    if image_content:
                        hospital.image.save(
                            f"{hospital_data['name'].replace(' ', '_').lower()}.jpg",
                            image_content,
                            save=True
                        )
                    
                    self.stdout.write(
                        self.style.SUCCESS(f"✓ Created: {hospital_data['name']} ({hospital_data['state']})")
                    )
                else:
                    self.stdout.write(
                        self.style.WARNING(f"⚠ Already exists: {hospital_data['name']} ({hospital_data['state']})")
                    )
                    
            except Exception as e:
                self.stdout.write(
                    self.style.ERROR(f"✗ Error creating {hospital_data['name']}: {e}")
                )
        
        total_hospitals = Hospital.objects.count()
        self.stdout.write(
            self.style.SUCCESS(f"\nPopulation complete! Total hospitals in database: {total_hospitals}")
        )
