# Generated by Django 5.2.5 on 2025-08-08 10:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctor_images/')),
                ('specialization', models.CharField(choices=[('general', 'General Medicine'), ('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('orthopedics', 'Orthopedics'), ('pediatrics', 'Pediatrics'), ('gynecology', 'Gynecology'), ('dermatology', 'Dermatology'), ('psychiatry', 'Psychiatry'), ('oncology', 'Oncology'), ('gastroenterology', 'Gastroenterology'), ('pulmonology', 'Pulmonology'), ('endocrinology', 'Endocrinology'), ('nephrology', 'Nephrology'), ('rheumatology', 'Rheumatology'), ('ophthalmology', 'Ophthalmology'), ('ent', 'ENT (Ear, Nose, Throat)'), ('anesthesiology', 'Anesthesiology'), ('radiology', 'Radiology'), ('pathology', 'Pathology'), ('surgery', 'General Surgery'), ('emergency', 'Emergency Medicine')], max_length=50)),
                ('qualification', models.CharField(max_length=100)),
                ('experience_years', models.PositiveIntegerField(default=0, help_text='Years of experience')),
                ('consultation_fee', models.PositiveIntegerField(default=500, help_text='Consultation fee in INR')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('available_days', models.CharField(default='Monday to Friday', help_text='Days when doctor is available', max_length=100)),
                ('available_time', models.CharField(default='9:00 AM - 5:00 PM', help_text='Time when doctor is available', max_length=100)),
                ('languages_spoken', models.CharField(default='English, Hindi', help_text='Languages the doctor can speak', max_length=200)),
                ('bio', models.TextField(blank=True, help_text="Doctor's biography", null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=4.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='hospitals.hospital')),
                ('user', models.OneToOneField(blank=True, help_text="Doctor's login account", null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ['name'],
            },
        ),
    ]
